export const OAUTH_ACCOUNT_SERVICE = Symbol('OAUTH_ACCOUNT_SERVICE');
export const OAUTH_ACCOUNT_REPOSITORY = Symbol('OAUTH_ACCOUNT_REPOSITORY');
export const OAUTH_ACCOUNT_MAPPERS = Symbol('OAUTH_ACCOUNT_MAPPERS');
